service:
  name: todo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  DB_PREFIX: ${self:provider.stage}-
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      ${opt:stage, 'development'}
    start:
      port: 8000
      inMemory: true
      # dbPath: './.dynamodb'
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: ${self:custom.DB_PREFIX}todos
            sources: [./migrations/todos-seed.json]

resources:
  Resources: ${file(migrations/todos.yml)}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local # Remember dynamodb-local first, then write serverless-offline
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-northeast-2
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:*:*"
  environment:
    NODE_DEV: ${self:provider.stage}
    DB_PREFIX: ${self:custom.DB_PREFIX}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

functions:
  - '${file(functions.yml)}'

package:
  exclude:
    - node_modules/**
    - migrations/**
    - .dynamodb/**
    # - .git/**